export const IUniswapV2 = [
  "function initialize(address token0, address token1, address fee_to) external",
  "function mint(address to) external returns (uint256)",
  "function burn(address to) external returns (uint256, uint256)",
  "function swap(uint256 amount0_out, uint256 amount1_out, address to, uint8[] memory data) external",
  "function name() external view returns (string memory)",
  "function symbol() external view returns (string memory)",
  "function decimals() external view returns (uint8)",
  "function totalSupply() external view returns (uint256)",
  "function balanceOf(address _address) external view returns (uint256)",
  "function allowance(address owner, address spender) external view returns (uint256)",
  "function approve(address spender, uint256 value) external returns (bool)",
  "function transfer(address to, uint256 value) external returns (bool)",
  "function transferFrom(address from, address to, uint256 value) external returns (bool)",
];
